export * from './interfaces/IBotActivity'
export * from './interfaces/IClient'
export * from './interfaces/IEvent'
export * from './interfaces/IExtendedInteraction'
export * from './interfaces/IRunOptions'
export * from './interfaces/ISpectrumClient'
export * from './interfaces/ISpectrumCommand'
export * from './interfaces/ISpectrumSubCommand'
